// Generated by https://quicktype.io

export interface PokemonQueryResult {
  count: number;
  next: string | null;
  previous: string | null;
  results: Result[];
}

export interface Result {
  name: string;
  url: string;
}